services:
  ram-ms-effect:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ram-ms-effect
    restart: unless-stopped
    ports:
      - '3003:3003'
    env_file:
      - .env
    depends_on:
      effect-db:
        condition: service_healthy
    networks:
      - ram-shared-network

  effect-db:
    image: mariadb:latest
    container_name: ram-ms-effect-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_PASSWORD:-ram_password}
      MARIADB_DATABASE: ${DATABASE_NAME:-ram-ms-effect-db}
      MARIADB_USER: ${DATABASE_USER:-user}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD:-ram_password}
    ports:
      - '3303:3306'
    volumes:
      - mariadb_data:/var/lib/mysql

    networks:
      - ram-shared-network
    healthcheck:
      test: [ 'CMD', 'healthcheck.sh', '--connect', '--innodb_initialized' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  ram-shared-network:
    external: true

volumes:
  mariadb_data:
